"""Integration tests for VRM to PMX conversion pipeline.

Tests that the full conversion path works correctly for various VRM profiles
without breaking backward compatibility.
"""
from __future__ import annotations

import sys
import unittest
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[2]
SRC_DIR = ROOT_DIR / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from mmd.VrmReader import VrmReader
from service.profile_detection import detect_profile


class ConversionPipelineTestCase(unittest.TestCase):
    """Test that conversion pipeline handles non-VRoid samples without issues."""

    def test_generic_vrm0_sample_detection(self):
        """Test that generic VRM0 models are correctly identified."""
        # Simulate a generic VRM0 model (no VRoid hints)
        vrm0_data = {
            "asset": {"generator": "UniVRM-0.95"},
            "extensions": {
                "VRM": {
                    "blendShapeMaster": {} 
                }
            }
        }
        result = detect_profile(vrm0_data, source_path="generic_character.vrm")
        
        self.assertEqual(result.profile, "generic")
        self.assertTrue(result.has_vrm0_extension)
        self.assertFalse(result.has_vrm1_extension)

    def test_generic_vrm1_sample_detection(self):
        """Test that generic VRM1.0 models (non-VRoid) are correctly identified."""
        # Simulate a generic VRM1.0 model generated by UniVRM
        vrm1_data = {
            "asset": {"generator": "UniVRM-1.30.0"},
            "extensions": {
                "VRMC_vrm": {
                    "expressions": {}
                }
            }
        }
        result = detect_profile(vrm1_data, source_path="humanoid_character.vrm")
        
        self.assertEqual(result.profile, "generic")
        self.assertTrue(result.has_vrm1_extension)
        self.assertFalse(result.has_vrm0_extension)

    def test_vroid_studio_vrm1_detection(self):
        """Test that VRoid Studio-generated models are detected as vroid."""
        vrm1_vroid_data = {
            "asset": {"generator": "VRoid Studio 2.1.0"},
            "extensions": {
                "VRMC_vrm": {
                    "expressions": {}
                }
            }
        }
        result = detect_profile(vrm1_vroid_data, source_path="avatar.vrm")
        
        self.assertEqual(result.profile, "vroid")
        self.assertTrue(result.has_vrm1_extension)

    def test_vroid_filename_hint_detection(self):
        """Test that vroid filename hint overrides generator."""
        # Some models may have "vroid" in filename even if generator is different
        ambiguous_data = {
            "asset": {"generator": "UniVRM"},
            "extensions": {"VRMC_vrm": {}}
        }
        result = detect_profile(ambiguous_data, source_path="vroid_style_char.vrm")
        
        self.assertEqual(result.profile, "vroid")
        self.assertIn("vroid", result.reason.lower())

    def test_reader_initialization_does_not_crash(self):
        """Test that VrmReader initializes without crashing on valid data."""
        # This ensures the profile detection doesn't break the conversion pipeline
        try:
            reader = VrmReader("test.vrm", is_check=False)
            # Initialization should succeed
            self.assertIsNotNone(reader)
        except Exception as e:
            self.fail(f"VrmReader initialization failed: {e}")

    def test_profile_detection_supports_both_vrm0_and_vrm1(self):
        """Test that detection pipeline supports both VRM formats."""
        profiles = []
        
        # Test VRM0
        vrm0 = detect_profile({"extensions": {"VRM": {}}}, "test0.vrm")
        profiles.append(vrm0)
        
        # Test VRM1
        vrm1 = detect_profile({"extensions": {"VRMC_vrm": {}}}, "test1.vrm")
        profiles.append(vrm1)
        
        # Should handle both without errors
        self.assertEqual(len(profiles), 2)
        self.assertTrue(all(p.profile in ["generic", "vroid"] for p in profiles))


class BackwardCompatibilityTestCase(unittest.TestCase):
    """Test that changes don't break existing VRM0 conversion."""

    def test_vrm0_without_vrm1_extension(self):
        """Ensure VRM0-only models are still supported."""
        vrm0_only = {
            "asset": {"generator": "Legacy VRM Exporter"},
            "extensions": {"VRM": {"blendShapeMaster": {}}}
        }
        result = detect_profile(vrm0_only, "legacy_model.vrm")
        
        self.assertEqual(result.profile, "generic")
        self.assertTrue(result.has_vrm0_extension)
        self.assertFalse(result.has_vrm1_extension)

    def test_mixed_vrm_extension_priority(self):
        """Test handling of models with both VRM0 and VRM1 extensions."""
        mixed = {
            "asset": {"generator": "Hybrid"},
            "extensions": {
                "VRM": {"blendShapeMaster": {}},
                "VRMC_vrm": {}
            }
        }
        result = detect_profile(mixed, "mixed.vrm")
        
        # Should still be detected correctly
        self.assertIn(result.profile, ["generic", "vroid"])


if __name__ == "__main__":
    unittest.main()
